pilot:
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 3
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
meshConfig:
  accessLogFile: /dev/stdout
  enableTracing: true
  defaultConfig:
    tracing:
      zipkin:
        address: jaeger-collector.observability:9411
    
