---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  encryptedData:
    bot_token: AgCHW0m12B7MAzoiC7luS9YOtlh8kEn/r9lT01Os80iHenzxAmXZsKLhMs+iM7b21J1jxf1arMFgOxZLPLrBwDJt058BDaM/ucRFCkDAr3fJ6Hnd4oke9/7YuOpDiqegvckyX2tftRBlq0V/nznpT5usZfC1Eg/hh2QFiblY8y8aAC5yUijO89ozyQcMcqJGVc3Nq+y1QUGFLA05IjBCuB6x7P03w9u54WTQsT1zr/mXq9Ga5RxjrCGWBQnyQXx1rrBE0IF446vc9uhTElLz6UIo195GBkkq7t47/iGuT8mKvDqu9LFxcZ+ru5A967QI66/Nm2JnLHqBEMbeNjsTWO/QLLha3R0o4GsOjxjDxt3V/t0ce9uSlbEfYYzS34Uz+goJDjI9q5Wu8l2L7wNOofFRhMmPmec0yatQKtpGkYcan5ROTPS94lNmwhW8phgLuU0N/pGosGCa0gsUDU1iHaSKhEpGsvEzoYXG2KMTu8x9yoRjvuut0dHMRwJway+ANVf3FpjHmH3i29ufeL3NHqLs5WkDS5ZePiEJ94BjLkWVJJZBx7078ByCKhyIQleNzkAKNZwrimIsyW2oM14plDfMFSMuGM9JemqE0DMmAdohhVDqeecdjO+rhrZeaK7/PYe6oC/9jKamyqlp8XlNJZNES2l02kba2VwhDw0YQDlN41NBYMFTrcRvw+pp8zfm6Jd+lIypFTP/gyuSVS5Rg2o7ptx1kpA7Y7t3si6HmGcxTTBz8WARJzAgj9+DJBm3
    chat_id: AgBAVpC8NhI3Zh1cU3+s0cvs4u+UPFoa/rlXrKDoSP+RR082bE9nMTF/+Gf3C23o8tLVw2VdLaYO6H9hfwGUzGhhXCf3LJVtgxotTBiT/rMCmHsg+gexnser5t+OrCovMyn+wq5zgFF+vNQ+eI21u9TMUqx4XNIsxcO0FSO4Zqziu4l5D1fELV6oVlsFt0rD2fTrOyFTHk3xVUODKOiezPZrpBQZp+/tOIALhhN64dP4xsF+M6HrKREOPKKQJTqo4dgh7fWh1isr44hZIht7XQF2/PTYpUpcA91DOuWRL9pEJKg4celWaT4w9kEbvDHGSJcTm8myHXsAfa+fELBpgGvBa32/BZcbxYXbW9gMQQgmUh7ahxqVu97AyVFuZy1TuZrawrmMY7HJV2K6lsNiSyx+wrkopK4beVF2+hYqoRZEUWHajvfaId31Egj5ZLdwigZer7lNoKMhqXw/HxKtGwDx4lhcGUMSjWHGm6ddraW9b/wK0Ap6qKd9CazTKQLVyWiiFrOtt5JtUYaoMmcmHoDKlarkzmLxfCH65ZpY0Y8QZwOjZSX49FdutOVPjyTCqZPFHmyHXB/VWm8vHrwWWopSabWTLt0OaKDK/2ka7rLRxWrIMq2ImLxUj1z5oav7Ogdt3sVcWEXMd5xJPNVXrxUk99e3imaQAVMInZbP3qWUdiS6fNefk5MPDhgAfTnqBTg4b8xZofcqiXjwjg==
  template:
    metadata:
      name: alertmanager-telegram
      namespace: monitoring
