---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-grafana-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBSNHW/GmH2Xo3PqUqx7NAUPX12EKQ4Spmbs+IpMh1+V6uWuqaeAtgzXYc6joy4Rd1R+ow/xzF6uAIm94iE7osLn9Q+Lk7vlM4jiR1YVLiWwjI711W7rBmsdN95vO88SLF69RzZoBjk3WK+ir7oHmRUuvFdzNMYNEUlzwX7tJj6Hlas9sH8m3lIRH3jjL4IJXQk5ozux4YKHmP2aDSTFzDhVGTMJv+AqYclLsvs+EyLmW8PiFWLLSzIUeh477/SavE5OVlC3zyxRESc7/1EwF6pg0w+9MaKGR7DpgRB3tC92OqukB5BichA3pNdOMFMAm3w4OQJnC3Wt4HgfwNw0DEGiBdcG5PNPxihb2/+zLnRnFWUsIaVn3ILs9cuTkF489o/i4Bg3XP47uGAWnVm6CrisgiMy8XL9sjg8mnl+uo4EOZ9OHpF4xhBTY1H6yXgXu67R2k3yUUzB3N9gUHjNPAk/wNgQHSiAxSyZreItitUrid1McUXqe9oXgkDEVMU6yP5MEblRvZOBc2/yfLZDSew3YE1umvIJJyq9AbGDs2GY82seY0iAHreIouhE79TowLL3FlbKuGv/H0qaje32idXqUUVHxYZtgyRw2AYLdiZ48QEGVa9oBB7oIjYNiMr8WWSM7rU+ZjMwvnhlaDFeZvmpIyEB1ole9vzeGBA72whUoCjq0YYaD4ThtMNdryhirjaPIbWnclrjaaNOwGbyw==
    admin-user: AgCOCv7IUOncMMp8Co5Ocv4JJPxVKlSQ0wqBi4Cx5vraxioassTHtkwOwbbYX0nl7fGIT5jrQvAQY8WQzR/38cY4da5vI+k/Zc+LGJ6ANGcsUqeRLZtUAHpO4v4iKaKLyxgm78tPktFaB5EKvyIgbfhhq/vEjqsawFy3qK8yGMin+XHVAcmHAdFZp9qKNc6hXc3VeciPQR0kLjfY3KSIKyifyHIwqFJjR15bYSdLau+C+/HLDln6q6w88c7N2FjgKDEcjc2eBTtdbxfcxXXliZsZPFB11MuwMLKRxUfhjygsGoc2JDs3GuBh9r2aNuwt0PeYr0gtDPMj1UK9wCYugdxrUHvnzdZQc8rxhxjWmnDV8t6l5ejpImfYCyEL0d7LxqASX9Zxm8u7aSDuoiCwWZ25KjVdw1vg5DcLO4x7t6KbFxJF1k7siGtkXmA+1N9qxPpcbUF3OXeFoLmyBKGbMTkkUxsJSbgbQm88pYJdWhLUm5NpFyujSPTZSJ2AUa0icKrSBAcMIe20Y5tnXd1gHOE5WzivYBhNPAx5WpNbdFn+WgORki0SkozhLQl5y5ZrVtS03L+XtJii/JBckpO4GTpQxKnmUZ3OwStguKA3NmTpphqJpBCe2g5BFCXmHT5l/eHPVbEppGIqW7/VGnKq9A2LiBY+6v5tYDHPoKr3hLUCsINh8ANtO+/wJqOgYe4+HqYvqTgYBg==
  template:
    metadata:
      name: monitoring-grafana-credentials
      namespace: monitoring
