nameOverride: "monitoring"

defaultRules:
  image: {}

alertmanager:
  alertmanagerSpec:
    env:
      - name: TELEGRAM_BOT_TOKEN
        valueFrom:
          secretKeyRef:
            name: alertmanager-telegram
            key: bot_token
      - name: TELEGRAM_CHAT_ID
        valueFrom:
          secretKeyRef:
            name: alertmanager-telegram
            key: chat_id

  config:
    route:
      group_by: ['namespace', 'alertname', 'severity']
      group_wait: 10s
      group_interval: 2m
      repeat_interval: 4h
      receiver: 'telegram'
      routes:
        - receiver: 'telegram'
          matchers:
            - alertname = "Watchdog"
    receivers:
      - name: 'telegram'
        telegram_configs:
          - api_url: 'https://api.telegram.org'
            bot_token: '$(TELEGRAM_BOT_TOKEN)'   # из Secret
            chat_id: '$(TELEGRAM_CHAT_ID)'        # из Secret
            parse_mode: 'HTML'
            send_resolved: true
            message: |
              {{- if eq .Status "firing" -}}
              🔥 <b>FIRING: {{ .Alerts | len }} alert(s)</b> 🔥
              {{- else -}}
              ✅ <b>RESOLVED: {{ .Alerts | len }} alert(s)</b> ✅
              {{- end -}}
              {{- range $idx, $alert := .Alerts }}
              {{- if eq $alert.Status "firing" -}}
                {{- if eq $alert.Labels.severity "critical" -}}🚨
                {{- else -}}⚠️
                {{- end -}}
              {{- else -}}✅
              {{- end -}} <b>{{ $alert.Labels.alertname }}</b>
              <b>Status:</b> {{ $alert.Status | title }}
              <b>Time:</b> {{ $alert.StartsAt.Format "15:04:05 02-01-2006" }}
              {{- if eq $alert.Status "resolved" }}
              <b>Duration:</b> {{ $alert.StartsAt.Sub $alert.EndsAt }}
              {{- end }}
              <b>Severity:</b> {{ $alert.Labels.severity | title }}
              <b>App:</b> {{ $alert.Labels.app }}
              <b>Namespace:</b> {{ $alert.Labels.namespace }}
              <b>Summary:</b> {{ $alert.Annotations.summary }}
              {{- if $alert.Annotations.description }}
              <b>Description:</b> {{ $alert.Annotations.description }}
              {{- end }}
              {{- if lt (add $idx 1) (len $.Alerts) }}
              ──────────────────────────────
              {{- end }}
              {{- end }}
    templates:
      - '/etc/alertmanager/templates/*.tmpl'

  alertmanagerSpec:
    volumes:
      - name: templates
        configMap:
          name: alertmanager-templates
    volumeMounts:
      - name: templates
        mountPath: /etc/alertmanager/templates

prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false

prometheusRules:
  enabled: true

nodeExporter:
  enabled: true
  hostRootfs: false

prometheus-node-exporter:
  hostRootFsMount:
    enabled: false