nameOverride: "monitoring"

defaultRules:
  image: {}

alertmanager:
  alertmanagerSpec:
    configSecret: alertmanager-monitoring-alertmanager
    volumes:
      - name: templates
        configMap:
          name: alertmanager-templates
    volumeMounts:
      - name: templates
        mountPath: /etc/alertmanager/templates

prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false

prometheusRules:
  enabled: true

nodeExporter:
  enabled: true
  hostRootfs: false

prometheus-node-exporter:
  hostRootFsMount:
    enabled: false