apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-operator
    targetRevision: 3.5.0 
    helm:
      values: |
        image:
          repository: docker.elastic.co/eck/eck-operator
          tag: 3.5.0
  destination:
    server: https://kubernetes.default.svc
    namespace: elasticsearch-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true