apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-kafka
  namespace: argocd
#  annotations:
#    argocd.argoproj.io/sync-wave: ""
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 32.4.3
    path: charts/apache-kafka
    helm:
      releaseName: apache-kafka
      values: |
        broker:
          replicaCount: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: apache-kafka
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true