apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: elasticsearch
      targetRevision: "21.*"
      helm:
        releaseName: elasticsearch
        valueFiles:
          - $values/charts/elasticsearch/values.yaml
    - repoURL: https://github.com/stickelite/infra-gitops
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true