apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "80.13.3"
      helm:
        releaseName: monitoring
        valueFiles:
          - $values/charts/kube-prometheus-stack/values.yaml
    - repoURL: https://github.com/stickelite/infra-gitops
      targetRevision: main
      ref: values
  ignoreDifferences:
    - group: monitoring.coreos.com
      kind: Prometheus
      jsonPointers:
        - /spec/enableOTLPReceiver
    - group: monitoring.coreos.com
      kind: Prometheus
      jsonPointers:
        - /spec/arbitraryFSAccessThroughSMs
    - group: monitoring.coreos.com
      kind: Alertmanager
      jsonPointers:
        - /spec/enableOTLPReceiver

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      